swagger: '2.0'
info: 
  title: Apostle music app server API Documentation
  description: API documentation for Apostle music app.
  version: 1.0
  contact: 
    email: successakinyemi365@gmail.com
  license:
    name: Apache 2.0
    url: 'http://apache.org/'
host: apostle.onrender.com
basePath: /               
schemes:
  - https

paths:
  /:
    get:
      summary: Home GET request
      description: Server base endpoint
      responses:
        200:
          description: Success

  /api/auth/register:
    post:
      summary: Register new user
      description: Register a user
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - email
              - name
              - password
            properties:
              email:
                type: string
              name:
                type: string
              password:
                type: string
      responses:
        201: 
          description: Signup successful verification OTP sent to user email address
        400:
          description: User error
        500: 
          description: Server error

  /api/auth/verifyOtp:
    post:
      summary: Verify OTP 
      description: Verify user email address with otp code
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - otp
            properties:
              otp:
                type: string
      responses:
        201: 
          description: Account Verified
        400:
          description: User error
        500: 
          description: Server error

  /api/auth/login:
    post:
      summary: User Login
      description: Login a user
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200: 
          description: Signup successful but account not verified
        201: 
          description: Signup successful, user data sent
        400:
          description: User error
        500: 
          description: Server error

  /api/auth/forgotPassword:
    post:
      summary: Forgot Password
      description: Forgot password request endpoint recives an email and send an OTP forgot password code to user email
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - email
            properties:
              email:
                type: string
      responses:
        200: 
          description: Reset password Otp successful sent
        400:
          description: User error
        500: 
          description: Server error

  /api/auth/resetPassword:
    post:
      summary: Reset Password
      description: Reset password request endpoint to update user password password reset OTP is required
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - otp
              - password
            properties:
              otp:
                type: string
              password:
                type: string
      responses:
        200: 
          description: Password reset successful
        400:
          description: User error
        500: 
          description: Server error

  /api/category/getAllCategory:
    get:
      summary: Get categories
      description: Get categories
      responses:
        200:
          description: Success
        500:
          description: Server Error

  /api/category/getCategory/categorySlug:
    get:
      summary: Get category
      description: Get category
      responses:
        200:
          description: Success
        500:
          description: Server Error
